### ISSUE TITLE
Hello Kyung

### ISSUE THREAD

**Issue by rruuaanng** [kkyungseo/kkyungseo#1]
Hey `Kyung`, maybe you didn't see the email I sent you, I'm a little interested in the `DevnovoS` organization on your homepage, I'm currently active in cpyhton, in the past I was active in the linux kernel and rtos communities, maybe we can get to know each other.

**Comment by kkyungseo** [comment]
Hey, rruuaanng!

I’ve been preparing for a data-related certification lately, so I had my GitHub notifications turned off these days. That’s probably why I was a bit slow to check the notifications. Thanks so much for reaching out!

DevnovoS is a project team I started with a close friend of mine who's a developer with a background in web publishing. We’re developing in Java since it's a language both my friend and I are comfortable with. We plan to set up the server using Docker.
Both of us are Korean, so we communicate primarily in Korean.

I took a look at your GitHub, and it seems like you're studying a slightly different field. If you're okay with using Java for development, we could have a deeper discussion about joining the project team. If you have any questions, feel free to ask!

Thanks!

**Comment by rruuaanng** [comment]
> Hey, rruuaanng!
> 
> I’ve been preparing for a data-related certification lately, so I had my GitHub notifications turned off these days. That’s probably why I was a bit slow to check the notifications. Thanks so much for reaching out!
> 
> DevnovoS is a project team I started with a close friend of mine who's a developer with a background in web publishing. We’re developing in Java since it's a language both my friend and I are comfortable with. We plan to set up the server using Docker. Both of us are Korean, so we communicate primarily in Korean.
> 
> I took a look at your GitHub, and it seems like you're studying a slightly different field. If you're okay with using Java for development, we could have a deeper discussion about joining the project team. If you have any questions, feel free to ask!
> 
> Thanks!

I'm okay with Java, but maybe not as skilled as you guys. I might need some info about your project. If you have a chat group, like on Discord, I’d like to join and connect with you. If it's possible, we can also communicate in English.

**Comment by kkyungseo** [comment]
We’re communicating through a free Slack channel right now, but if needed, I can set up an additional Discord server.
We're not quite at a professional level yet, but we can definitely communicate in English.
However, the plans and ideas we've written so far are in Korean, so we’d need some time to translate them. 
Also, I’ll need to discuss things with my friend who's part of the team. 
Since it’s the weekend in Korea, it’ll be easier to reach her on Monday.
Could you wait up to three days for these things?

**Comment by rruuaanng** [comment]
> We’re communicating through a free Slack channel right now, but if needed, I can set up an additional Discord server. We're not quite at a professional level yet, but we can definitely communicate in English. However, the plans and ideas we've written so far are in Korean, so we’d need some time to translate them. Also, I’ll need to discuss things with my friend who's part of the team. Since it’s the weekend in Korea, it’ll be easier to reach her on Monday. Could you wait up to three days for these things?

No problem, look forward to your reply on monday, of course it's best to use email.
